#default 공통설정
spring:
  jpa:
    show-sql: true
    properties:
      jdbc:
        time_zone: Asia/Seoul
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

--- # local
spring:
  config:
    activate:
      on-profile: "db-local"
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:localdb
  h2:
    console:
      enabled: true

--- #dev
spring:
  config:
    activate:
      on-profile: "db-dev"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-nxkvugrrf5-stack-awsebrdsdatabase-wlkhngxcbsrx.cbwccmwigr9w.ap-northeast-2.rds.amazonaws.com:3306/ebdb
    username: cseSoonNyang
    password: snsn22cse